name: Frontend Pipeline
on:
  push:
    branches:
      - 204175A
  pull_request:
    branches:
      - 204175A

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
      CHROME_BIN: /usr/bin/google-chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/UI/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create .env file
        working-directory: UI
        run: |
          echo "BASE_URL=https://cargillsonline.com/" > .env
          echo "LOGIN_TEXT=geshanpasindu4@gmail.com" >> .env
          echo "PASSWORD=Gesh@1234" >> .env

      - name: Install Latest Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver for Chrome 131.0.6778.204
        run: |
          CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip"
          wget -N "${CHROMEDRIVER_URL}" -P /tmp
          unzip /tmp/chromedriver-linux64.zip -d /tmp/chromedriver-linux64/
          mkdir -p UI/src/test/resources/driver/
          mv /tmp/chromedriver-linux64/chromedriver-linux64/chromedriver UI/src/test/resources/driver/chromedriver
          chmod +x UI/src/test/resources/driver/chromedriver

      - name: Install XVFB
        run: |
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3

      - name: Verify Chrome and ChromeDriver Versions
        run: |
          google-chrome --version
          UI/src/test/resources/driver/chromedriver --version

      - name: Set up Chrome for testing
        run: |
          sudo chown root:root /opt/google/chrome/chrome-sandbox
          sudo chmod 4755 /opt/google/chrome/chrome-sandbox

      - name: Install Maven dependencies
        run: mvn install -DskipTests
        working-directory: UI

      - name: Run tests and generate Allure results
        run: |
          mvn test -Dsurefire.suiteXmlFiles=testng.xml \
            -Dallure.results.directory=target/allure-results \
            -Dwebdriver.chrome.driver=UI/src/test/resources/driver/chromedriver \
            -Dchrome.options="--headless=new --disable-gpu --no-sandbox --disable-dev-shm-usage --window-size=1920,1080 --remote-allow-origins=* --disable-extensions --disable-software-rasterizer"
        working-directory: UI
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results --clean -o target/allure-report
        working-directory: UI

      - name: Debug Allure Report Folder
        run: ls -R UI/target/allure-report

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: UI/target/allure-report
          
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            UI/target/surefire-reports/
            UI/target/logs/    
