name: Selenium Cucumber TestNG Pipeline

on:
  push:
    branches:
      - 204175A
  pull_request:
    branches:
      - 204175A

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/UI/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Google Chrome
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 5: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          # Fetch installed Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -n 1)
          echo "Detected Chrome version: $CHROME_VERSION"
          
          # Fetch corresponding ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          # Ensure the version is valid and handle errors
          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "Error: ChromeDriver version for $CHROME_VERSION not found. Falling back to the latest stable version."
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi
          
          # Download and unzip the appropriate ChromeDriver version
          wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P /tmp
          unzip /tmp/chromedriver_linux64.zip -d /tmp
          
          # Move to the correct path
          mkdir -p UI/src/test/resources/driver/
          mv /tmp/chromedriver UI/src/test/resources/driver/chromedriver
          chmod +x UI/src/test/resources/driver/chromedriver
          echo "ChromeDriver placed at UI/src/test/resources/driver/chromedriver"

      # Step 6: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install -DskipTests
        working-directory: UI

      # Step 7: Run tests in headless mode and generate Allure results
      - name: Run tests and generate Allure results
        run: |
          mvn test -Dsurefire.suiteXmlFiles=testng.xml \
            -Dallure.results.directory=target/allure-results \
            -Dwebdriver.chrome.driver=UI/src/test/resources/driver/chromedriver \
            -Dchrome.options="--headless --no-sandbox --disable-dev-shm-usage"
        working-directory: UI

      # Step 8: Generate Allure HTML report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results -o target/allure-report --clean
        working-directory: UI

      # Step 9: Upload Allure HTML report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: UI/target/allure-report
