name: Selenium Cucumber TestNG Pipeline

on:
  push:
    branches:
      - 204175A
  pull_request:
    branches:
      - 204175A

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/UI/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Check Chrome version
      - name: Check Chrome version
        id: chrome-version
        run: google-chrome --version

      # Step 5: Extract Chrome version and download Chromedriver
      - name: Download Chromedriver
        run: |
          sudo apt-get install -y unzip
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          echo "Chrome Version: $CHROME_VERSION"
          echo "Chromedriver Version: $DRIVER_VERSION"
          wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Step 6: Install Maven dependencies
      - name: Install dependencies
        run: mvn install -DskipTests
        working-directory: UI

      # Step 7: Run tests and generate Allure results
      - name: Run tests and generate Allure results
        run: mvn test -Dsurefire.suiteXmlFiles=testng.xml -Dallure.results.directory=target/allure-results
        working-directory: UI

      # Step 8: Generate Allure HTML report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results -o target/allure-report --clean
        working-directory: UI

      # Step 9: Upload Allure HTML report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: UI/target/allure-report
